CREATE TABLE IF NOT EXISTS "schedules" (
  "season" INTEGER NOT NULL,
  "game_date_str" VARCHAR(8) NOT NULL,
  "game_number" INTEGER NOT NULL,
  "visitors_team" VARCHAR(3) NOT NULL,
  "home_team" VARCHAR(3) NOT NULL,
  "game_month" INTEGER NOT NULL,
  "game_month_day" INTEGER NOT NULL,
  "week_day" INTEGER NOT NULL,
  "visitors_league" VARCHAR(3) NOT NULL,
  "visitors_season_game_number" INTEGER NOT NULL,
  "home_league" VARCHAR(3) NOT NULL,
  "home_season_game_number" INTEGER NOT NULL,
  "game_type" VARCHAR(1) NOT NULL,
  "postponed_canceled" VARCHAR(128) NOT NULL DEFAULT '',
  "make_up_date" VARCHAR(128) NOT NULL DEFAULT '',

  PRIMARY KEY(season, game_date_str, game_number, visitors_team, home_team, visitors_season_game_number)
);
CREATE TABLE IF NOT EXISTS "gamelogs" (
  "season" INTEGER NOT NULL,
  "game_date_str" VARCHAR(8) NOT NULL,
  "game_month" INTEGER NOT NULL,
  "game_month_day" INTEGER NOT NULL,
  "game_number" INTEGER NOT NULL, 
  "week_day" INTEGER NOT NULL,
  "visitors_team" VARCHAR(3) NOT NULL,
  "visitors_league" VARCHAR(3) NOT NULL,
  "visitors_season_game_number" INTEGER NOT NULL,
  "home_team" VARCHAR(3) NOT NULL,
  "home_league" VARCHAR(3) NOT NULL,
  "home_season_game_number" INTEGER NOT NULL,
  "visitors_score" INTEGER NOT NULL,
  "home_score" INTEGER NOT NULL,
  "game_outs" INTEGER NOT NULL,
  "game_type" VARCHAR(1) NOT NULL,
  "completion_information" VARCHAR(128) NOT NULL DEFAULT '',
  "forfeit_information" VARCHAR(128) NOT NULL DEFAULT '',
  "protest_information" VARCHAR(128) NOT NULL DEFAULT '',
  "park_id" VARCHAR(5) NOT NULL DEFAULT '',
  "attendance" INTEGER NOT NULL,
  "game_time_in_minutes" INTEGER NOT NULL,
  "visitors_line_score" VARCHAR(32) NOT NULL DEFAULT '',
  "home_line_score" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_ab" INTEGER NOT NULL DEFAULT 0,
  "visitors_h" INTEGER NOT NULL DEFAULT 0,
  "visitors_doubles" INTEGER NOT NULL DEFAULT 0,
  "visitors_triples" INTEGER NOT NULL DEFAULT 0,
  "visitors_hr" INTEGER NOT NULL DEFAULT 0,
  "visitors_rbi" INTEGER NOT NULL DEFAULT 0,
  "visitors_sac_hits" INTEGER NOT NULL DEFAULT 0,
  "visitors_sac_flies" INTEGER NOT NULL DEFAULT 0,
  "visitors_hbp" INTEGER NOT NULL DEFAULT 0,
  "visitors_bb" INTEGER NOT NULL DEFAULT 0,
  "visitors_ibb" INTEGER NOT NULL DEFAULT 0,
  "visitors_k" INTEGER NOT NULL DEFAULT 0,
  "visitors_sb" INTEGER NOT NULL DEFAULT 0,
  "visitors_cs" INTEGER NOT NULL DEFAULT 0,
  "visitors_gidp" INTEGER NOT NULL DEFAULT 0,
  "visitors_catcher_interference" INTEGER NOT NULL DEFAULT 0,
  "visitors_lob" INTEGER NOT NULL DEFAULT 0,
  "visitors_pitchers_used" INTEGER NOT NULL DEFAULT 0,
  "visitors_individual_er" INTEGER NOT NULL DEFAULT 0,
  "visitors_team_er" INTEGER NOT NULL DEFAULT 0,
  "visitors_wp" INTEGER NOT NULL DEFAULT 0,
  "visitors_balks" INTEGER NOT NULL DEFAULT 0,
  "visitors_po" INTEGER NOT NULL DEFAULT 0,
  "visitors_a" INTEGER NOT NULL DEFAULT 0,
  "visitors_e" INTEGER NOT NULL DEFAULT 0,
  "visitors_pb" INTEGER NOT NULL DEFAULT 0,
  "visitors_dp" INTEGER NOT NULL DEFAULT 0,
  "visitors_triple_plays" INTEGER NOT NULL DEFAULT 0,
  "home_ab" INTEGER NOT NULL DEFAULT 0,
  "home_h" INTEGER NOT NULL DEFAULT 0,
  "home_doubles" INTEGER NOT NULL DEFAULT 0,
  "home_triples" INTEGER NOT NULL DEFAULT 0,
  "home_hr" INTEGER NOT NULL DEFAULT 0,
  "home_rbi" INTEGER NOT NULL DEFAULT 0,
  "home_sac_hits" INTEGER NOT NULL DEFAULT 0,
  "home_sac_flies" INTEGER NOT NULL DEFAULT 0,
  "home_hbp" INTEGER NOT NULL DEFAULT 0,
  "home_bb" INTEGER NOT NULL DEFAULT 0,
  "home_ibb" INTEGER NOT NULL DEFAULT 0,
  "home_k" INTEGER NOT NULL DEFAULT 0,
  "home_sb" INTEGER NOT NULL DEFAULT 0,
  "home_cs" INTEGER NOT NULL DEFAULT 0,
  "home_gidp" INTEGER NOT NULL DEFAULT 0,
  "home_catcher_interference" INTEGER NOT NULL DEFAULT 0,
  "home_lob" INTEGER NOT NULL DEFAULT 0,
  "home_pitchers_used" INTEGER NOT NULL DEFAULT 0,
  "home_individual_er" INTEGER NOT NULL DEFAULT 0,
  "home_team_er" INTEGER NOT NULL DEFAULT 0,
  "home_wp" INTEGER NOT NULL DEFAULT 0,
  "home_balks" INTEGER NOT NULL DEFAULT 0,
  "home_po" INTEGER NOT NULL DEFAULT 0,
  "home_a" INTEGER NOT NULL DEFAULT 0,
  "home_e" INTEGER NOT NULL DEFAULT 0,
  "home_pb" INTEGER NOT NULL DEFAULT 0,
  "home_dp" INTEGER NOT NULL DEFAULT 0,
  "home_triple_plays" INTEGER NOT NULL DEFAULT 0,
  "home_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "first_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "first_base_ump_name"  VARCHAR(32) NOT NULL DEFAULT '',
  "second_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "second_base_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "third_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "third_base_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "lf_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "lf_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "rf_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "rf_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_mgr_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitors_mgr_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_mgr_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_mgr_name" VARCHAR(32) NOT NULL DEFAULT '',
  "winning_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "winning_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "losing_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "losing_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "saving_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "saving_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_starting_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitors_starting_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_starting_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_starting_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "game_winning_rbi_batter_id" VARCHAR(8) NOT NULL DEFAULT '',
  "game_winning_rbi_batter_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter1_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter1_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter1_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter2_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter2_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter2_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter3_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter3_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter3_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter4_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter4_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter4_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter5_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter5_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter5_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter6_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter6_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter6_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter7_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter7_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter7_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter8_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter8_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter8_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter9_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter9_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter9_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter1_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter1_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter1_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter2_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter2_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter2_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter3_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter3_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter3_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter4_id" VARCHAR(8) NOT NULL DEFAULT '', 
  "home_batter4_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter4_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter5_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter5_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter5_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter6_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter6_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter6_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter7_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter7_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter7_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter8_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter8_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter8_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter9_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter9_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter9_pos" INTEGER NOT NULL DEFAULT 0,
  "additional_information" VARCHAR(128) NOT NULL DEFAULT '',
  "acquisition_information" VARCHAR(64) NOT NULL DEFAULT '',

  PRIMARY KEY(season, game_date_str, game_number, visitors_team, home_team, visitors_season_game_number)
);
