CREATE TABLE IF NOT EXISTS "schedules" (
  "season" INTEGER NOT NULL,
  "game_date_str" VARCHAR(8) NOT NULL,
  "game_number" INTEGER NOT NULL,
  "visitors_team" VARCHAR(3) NOT NULL,
  "home_team" VARCHAR(3) NOT NULL,
  "game_month" INTEGER NOT NULL,
  "game_month_day" INTEGER NOT NULL,
  "week_day" INTEGER NOT NULL,
  "visitors_league" VARCHAR(3) NOT NULL,
  "visitors_season_game_number" INTEGER NOT NULL,
  "home_league" VARCHAR(3) NOT NULL,
  "home_season_game_number" INTEGER NOT NULL,
  "game_type" VARCHAR(1) NOT NULL,
  "postponed_canceled" VARCHAR(128) NOT NULL DEFAULT '',
  "make_up_date" VARCHAR(128) NOT NULL DEFAULT '',

  PRIMARY KEY(season, game_date_str, game_number, visitors_team, home_team, visitors_season_game_number)
);
CREATE TABLE IF NOT EXISTS "gamelogs" (
  "season" INTEGER NOT NULL,
  "game_date_str" VARCHAR(8) NOT NULL,
  "game_month" INTEGER NOT NULL,
  "game_month_day" INTEGER NOT NULL,
  "game_number" INTEGER NOT NULL, 
  "week_day" INTEGER NOT NULL,
  "visitors_team" VARCHAR(3) NOT NULL,
  "visitors_league" VARCHAR(3) NOT NULL,
  "visitors_season_game_number" INTEGER NOT NULL,
  "home_team" VARCHAR(3) NOT NULL,
  "home_league" VARCHAR(3) NOT NULL,
  "home_season_game_number" INTEGER NOT NULL,
  "visitors_score" INTEGER NOT NULL,
  "home_score" INTEGER NOT NULL,
  "game_outs" INTEGER NOT NULL,
  "game_type" VARCHAR(1) NOT NULL,
  "completion_information" VARCHAR(128) NOT NULL DEFAULT '',
  "forfeit_information" VARCHAR(128) NOT NULL DEFAULT '',
  "protest_information" VARCHAR(128) NOT NULL DEFAULT '',
  "park_id" VARCHAR(5) NOT NULL DEFAULT '',
  "attendance" INTEGER NOT NULL,
  "game_time_in_minutes" INTEGER NOT NULL,
  "visitors_line_score" VARCHAR(32) NOT NULL DEFAULT '',
  "home_line_score" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_ab" INTEGER NOT NULL DEFAULT 0,
  "visitors_h" INTEGER NOT NULL DEFAULT 0,
  "visitors_doubles" INTEGER NOT NULL DEFAULT 0,
  "visitors_triples" INTEGER NOT NULL DEFAULT 0,
  "visitors_hr" INTEGER NOT NULL DEFAULT 0,
  "visitors_rbi" INTEGER NOT NULL DEFAULT 0,
  "visitors_sac_hits" INTEGER NOT NULL DEFAULT 0,
  "visitors_sac_flies" INTEGER NOT NULL DEFAULT 0,
  "visitors_hbp" INTEGER NOT NULL DEFAULT 0,
  "visitors_bb" INTEGER NOT NULL DEFAULT 0,
  "visitors_ibb" INTEGER NOT NULL DEFAULT 0,
  "visitors_k" INTEGER NOT NULL DEFAULT 0,
  "visitors_sb" INTEGER NOT NULL DEFAULT 0,
  "visitors_cs" INTEGER NOT NULL DEFAULT 0,
  "visitors_gidp" INTEGER NOT NULL DEFAULT 0,
  "visitors_catcher_interference" INTEGER NOT NULL DEFAULT 0,
  "visitors_lob" INTEGER NOT NULL DEFAULT 0,
  "visitors_pitchers_used" INTEGER NOT NULL DEFAULT 0,
  "visitors_individual_er" INTEGER NOT NULL DEFAULT 0,
  "visitors_team_er" INTEGER NOT NULL DEFAULT 0,
  "visitors_wp" INTEGER NOT NULL DEFAULT 0,
  "visitors_balks" INTEGER NOT NULL DEFAULT 0,
  "visitors_po" INTEGER NOT NULL DEFAULT 0,
  "visitors_a" INTEGER NOT NULL DEFAULT 0,
  "visitors_e" INTEGER NOT NULL DEFAULT 0,
  "visitors_pb" INTEGER NOT NULL DEFAULT 0,
  "visitors_dp" INTEGER NOT NULL DEFAULT 0,
  "visitors_triple_plays" INTEGER NOT NULL DEFAULT 0,
  "home_ab" INTEGER NOT NULL DEFAULT 0,
  "home_h" INTEGER NOT NULL DEFAULT 0,
  "home_doubles" INTEGER NOT NULL DEFAULT 0,
  "home_triples" INTEGER NOT NULL DEFAULT 0,
  "home_hr" INTEGER NOT NULL DEFAULT 0,
  "home_rbi" INTEGER NOT NULL DEFAULT 0,
  "home_sac_hits" INTEGER NOT NULL DEFAULT 0,
  "home_sac_flies" INTEGER NOT NULL DEFAULT 0,
  "home_hbp" INTEGER NOT NULL DEFAULT 0,
  "home_bb" INTEGER NOT NULL DEFAULT 0,
  "home_ibb" INTEGER NOT NULL DEFAULT 0,
  "home_k" INTEGER NOT NULL DEFAULT 0,
  "home_sb" INTEGER NOT NULL DEFAULT 0,
  "home_cs" INTEGER NOT NULL DEFAULT 0,
  "home_gidp" INTEGER NOT NULL DEFAULT 0,
  "home_catcher_interference" INTEGER NOT NULL DEFAULT 0,
  "home_lob" INTEGER NOT NULL DEFAULT 0,
  "home_pitchers_used" INTEGER NOT NULL DEFAULT 0,
  "home_individual_er" INTEGER NOT NULL DEFAULT 0,
  "home_team_er" INTEGER NOT NULL DEFAULT 0,
  "home_wp" INTEGER NOT NULL DEFAULT 0,
  "home_balks" INTEGER NOT NULL DEFAULT 0,
  "home_po" INTEGER NOT NULL DEFAULT 0,
  "home_a" INTEGER NOT NULL DEFAULT 0,
  "home_e" INTEGER NOT NULL DEFAULT 0,
  "home_pb" INTEGER NOT NULL DEFAULT 0,
  "home_dp" INTEGER NOT NULL DEFAULT 0,
  "home_triple_plays" INTEGER NOT NULL DEFAULT 0,
  "home_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "first_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "first_base_ump_name"  VARCHAR(32) NOT NULL DEFAULT '',
  "second_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "second_base_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "third_base_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "third_base_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "lf_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "lf_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "rf_ump_id" VARCHAR(8) NOT NULL DEFAULT '',
  "rf_ump_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_mgr_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitors_mgr_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_mgr_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_mgr_name" VARCHAR(32) NOT NULL DEFAULT '',
  "winning_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "winning_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "losing_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "losing_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "saving_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "saving_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitors_starting_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitors_starting_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_starting_pitcher_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_starting_pitcher_name" VARCHAR(32) NOT NULL DEFAULT '',
  "game_winning_rbi_batter_id" VARCHAR(8) NOT NULL DEFAULT '',
  "game_winning_rbi_batter_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter1_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter1_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter1_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter2_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter2_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter2_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter3_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter3_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter3_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter4_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter4_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter4_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter5_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter5_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter5_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter6_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter6_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter6_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter7_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter7_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter7_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter8_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter8_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter8_pos" INTEGER NOT NULL DEFAULT 0,
  "visitor_batter9_id" VARCHAR(8) NOT NULL DEFAULT '',
  "visitor_batter9_name" VARCHAR(32) NOT NULL DEFAULT '',
  "visitor_batter9_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter1_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter1_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter1_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter2_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter2_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter2_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter3_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter3_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter3_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter4_id" VARCHAR(8) NOT NULL DEFAULT '', 
  "home_batter4_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter4_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter5_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter5_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter5_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter6_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter6_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter6_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter7_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter7_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter7_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter8_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter8_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter8_pos" INTEGER NOT NULL DEFAULT 0,
  "home_batter9_id" VARCHAR(8) NOT NULL DEFAULT '',
  "home_batter9_name" VARCHAR(32) NOT NULL DEFAULT '',
  "home_batter9_pos" INTEGER NOT NULL DEFAULT 0,
  "additional_information" VARCHAR(128) NOT NULL DEFAULT '',
  "acquisition_information" VARCHAR(64) NOT NULL DEFAULT '',

  PRIMARY KEY(season, game_date_str, game_number, visitors_team, home_team, visitors_season_game_number)
);
CREATE TABLE IF NOT EXISTS "allstarfull" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "gameNum" INTEGER, "gameID" VARCHAR(255) DEFAULT '', "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "GP" INTEGER, "startingPos" INTEGER, PRIMARY KEY ("playerID", "yearID", "gameNum"));
CREATE TABLE IF NOT EXISTS "appearances" ("yearID" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "playerID" VARCHAR(255) DEFAULT '', "G_all" INTEGER, "GS" INTEGER, "G_batting" INTEGER, "G_defense" INTEGER, "G_p" INTEGER, "G_c" INTEGER, "G_1b" INTEGER, "G_2b" INTEGER, "G_3b" INTEGER, "G_ss" INTEGER, "G_lf" INTEGER, "G_cf" INTEGER, "G_rf" INTEGER, "G_of" INTEGER, "G_dh" INTEGER, "G_ph" INTEGER, "G_pr" INTEGER, PRIMARY KEY ("yearID", "teamID", "playerID", "G_all"));
CREATE TABLE IF NOT EXISTS "awardsmanagers" ("playerID" VARCHAR(255) DEFAULT '', "awardID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "tie" VARCHAR(255) DEFAULT '', "notes" VARCHAR(255) DEFAULT '', PRIMARY KEY ("yearID", "lgID", "awardID", "playerID"));
CREATE TABLE IF NOT EXISTS "awardsplayers" ("playerID" VARCHAR(255) DEFAULT '', "awardID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "tie" VARCHAR(255) DEFAULT '', "notes" VARCHAR(255) DEFAULT '', PRIMARY KEY ("yearID", "lgID", "awardID", "playerID"));
CREATE TABLE IF NOT EXISTS "awardssharemanagers" ("awardID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "playerID" VARCHAR(255) DEFAULT '', "pointsWon" INTEGER, "pointsMax" INTEGER, "votesFirst" INTEGER, PRIMARY KEY ("awardID", "yearID", "lgID", "playerID"));
CREATE TABLE IF NOT EXISTS "awardsshareplayers" ("awardID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "playerID" VARCHAR(255) DEFAULT '', "pointsWon" DECIMAL(10, 5), "pointsMax" INTEGER, "votesFirst" DECIMAL(10, 5), PRIMARY KEY ("awardID", "yearID", "lgID", "playerID"));
CREATE TABLE IF NOT EXISTS "batting" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "stint" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "G" INTEGER, "AB" INTEGER, "R" INTEGER, "H" INTEGER, "doubles" INTEGER, "triples" INTEGER, "HR" INTEGER, "RBI" INTEGER, "SB" INTEGER, "CS" INTEGER, "BB" INTEGER, "SO" INTEGER, "IBB" INTEGER, "HBP" INTEGER, "SH" INTEGER, "SF" INTEGER, "GIDP" INTEGER, PRIMARY KEY ("playerID", "yearID", "teamID", "stint"));
CREATE TABLE IF NOT EXISTS "battingpost" ("yearID" INTEGER, "round" VARCHAR(255) DEFAULT '', "playerID" VARCHAR(255) DEFAULT '', "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "G" INTEGER, "AB" INTEGER, "R" INTEGER, "H" INTEGER, "doubles" INTEGER, "triples" INTEGER, "HR" INTEGER, "RBI" INTEGER, "SB" INTEGER, "CS" INTEGER, "BB" INTEGER, "SO" INTEGER, "IBB" INTEGER, "HBP" INTEGER, "SH" INTEGER, "SF" INTEGER, "GIDP" INTEGER, PRIMARY KEY ("yearID", "round", "playerID", "teamID"));
CREATE TABLE IF NOT EXISTS "collegeplaying" ("playerID" VARCHAR(255) DEFAULT '', "schoolID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, PRIMARY KEY ("playerID", "schoolID", "yearID"));
CREATE TABLE IF NOT EXISTS "fielding" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "stint" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "POS" VARCHAR(255) DEFAULT '', "A" INTEGER, "GS" INTEGER, "G" INTEGER, "PB" INTEGER, "InnOuts" INTEGER, "ZR" INTEGER, "PO" INTEGER, "WP" INTEGER, "CS" INTEGER, "E" INTEGER, "DP" INTEGER, "SB" INTEGER, PRIMARY KEY ("playerID", "yearID", "teamID", "POS", "stint"));
CREATE TABLE IF NOT EXISTS "fieldingof" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "stint" INTEGER, "Glf" INTEGER, "Gcf" INTEGER, "Grf" INTEGER, PRIMARY KEY ("playerID", "yearID", "stint"));
CREATE TABLE IF NOT EXISTS "fieldingofsplit" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "stint" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "POS" VARCHAR(255) DEFAULT '', "G" INTEGER, "GS" INTEGER, "InnOuts" INTEGER, "PO" INTEGER, "A" INTEGER, "E" INTEGER, "DP" INTEGER, "PB" INTEGER, "WP" INTEGER, "SB" INTEGER, "CS" INTEGER, "ZR" INTEGER, PRIMARY KEY ("playerID", "yearID", "teamID", "POS", "stint"));
CREATE TABLE IF NOT EXISTS "fieldingpost" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "round" VARCHAR(255) DEFAULT '', "POS" VARCHAR(255) DEFAULT '', "G" INTEGER, "GS" INTEGER, "InnOuts" INTEGER, "PO" INTEGER, "A" INTEGER, "E" INTEGER, "DP" INTEGER, "TP" INTEGER, "PB" INTEGER, "SB" INTEGER, "CS" INTEGER, PRIMARY KEY ("playerID", "yearID", "round", "POS"));
CREATE TABLE IF NOT EXISTS "halloffame" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "votedBy" VARCHAR(255) DEFAULT '', "ballots" INTEGER, "needed" INTEGER, "votes" INTEGER, "inducted" VARCHAR(255) DEFAULT '', "category" VARCHAR(255) DEFAULT '', "needed_note" VARCHAR(255) DEFAULT '', PRIMARY KEY ("playerID", "category", "yearID", "votedBy"));
CREATE TABLE IF NOT EXISTS "homegames" ("yearkey" INTEGER, "parkkey" VARCHAR(255) DEFAULT '', "teamkey" VARCHAR(255) DEFAULT '', "leaguekey" VARCHAR(255) DEFAULT '', "attendance" INTEGER, "games" INTEGER, "spanfirst" VARCHAR(255) DEFAULT '', "spanlast" VARCHAR(255) DEFAULT '', "openings" INTEGER, PRIMARY KEY ("yearkey", "parkkey", "teamkey"));
CREATE TABLE IF NOT EXISTS "managers" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "teamID" VARCHAR(255) NOT NULL, "lgID" VARCHAR(255) NOT NULL, "inseason" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER, "rank" INTEGER, "plyrMgr" VARCHAR(255) DEFAULT '', PRIMARY KEY ("yearID", "lgID", "teamID", "playerID", "inseason"));
CREATE TABLE IF NOT EXISTS "managershalf" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "inseason" INTEGER, "half" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER, "rank" INTEGER, PRIMARY KEY ("playerID", "teamID", "lgID", "yearID", "half"));
CREATE TABLE IF NOT EXISTS "parks" ("parkkey" VARCHAR(255) PRIMARY KEY, "parkname" VARCHAR(255) DEFAULT '', "parkalias" VARCHAR(255) DEFAULT '', "alias" VARCHAR(255) DEFAULT '', "city" VARCHAR(255) DEFAULT '', "state" VARCHAR(255) DEFAULT '', "country" VARCHAR(255));
CREATE TABLE IF NOT EXISTS "people" ("playerID" VARCHAR(9) PRIMARY KEY, "birthYear" INTEGER, "birthMonth" INTEGER, "birthDay" INTEGER, "birthCountry" VARCHAR(14), "birthState" VARCHAR(22), "birthCity" VARCHAR(26), "deathYear" INTEGER, "deathMonth" INTEGER, "deathDay" INTEGER, "deathCountry" VARCHAR(14) DEFAULT '', "deathState" VARCHAR(20) DEFAULT '', "deathCity" VARCHAR(28) DEFAULT '', "nameFirst" VARCHAR(12), "nameLast" VARCHAR(14), "nameGiven" VARCHAR(43), "weight" INTEGER, "height" INTEGER, "bats" VARCHAR(255) DEFAULT '', "throws" VARCHAR(255) DEFAULT '', "debut" VARCHAR(255) DEFAULT '', "finalGame" VARCHAR(255) DEFAULT '', "retroID" VARCHAR(255) DEFAULT '', "bbrefID" VARCHAR(9));
CREATE TABLE IF NOT EXISTS "pitching" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "stint" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "W" INTEGER, "L" INTEGER, "G" INTEGER, "GS" INTEGER, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "H" INTEGER, "ER" INTEGER, "HR" INTEGER, "BB" INTEGER, "SO" INTEGER, "BAOpp" REAL, "ERA" REAL, "IBB" INTEGER, "WP" INTEGER, "HBP" INTEGER, "BK" INTEGER, "BFP" INTEGER, "GF" INTEGER, "R" INTEGER, "SH" INTEGER, "SF" INTEGER, "GIDP" INTEGER, PRIMARY KEY ("playerID", "yearID", "stint", "teamID"));
CREATE TABLE IF NOT EXISTS "pitchingpost" ("playerID" VARCHAR(255) DEFAULT '', "yearID" INTEGER, "round" VARCHAR(255) DEFAULT '', "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "W" INTEGER, "L" INTEGER, "G" INTEGER, "GS" INTEGER, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "H" INTEGER, "ER" INTEGER, "HR" INTEGER, "BB" INTEGER, "SO" INTEGER, "BAOpp" REAL, "ERA" REAL, "IBB" INTEGER, "WP" INTEGER, "HBP" INTEGER, "BK" INTEGER, "BFP" INTEGER, "GF" INTEGER, "R" INTEGER, "SH" INTEGER, "SF" INTEGER, "GIDP" INTEGER, PRIMARY KEY ("playerID", "yearID", "round"));
CREATE TABLE IF NOT EXISTS "salaries" ("yearID" INTEGER, "teamID" VARCHAR(255) DEFAULT '', "lgID" VARCHAR(255) DEFAULT '', "playerID" VARCHAR(255) DEFAULT '', "salary" INTEGER, PRIMARY KEY ("yearID", "teamID", "playerID"));
CREATE TABLE IF NOT EXISTS "schools" ("schoolID" VARCHAR(255) PRIMARY KEY, "name_full" VARCHAR(255) DEFAULT '', "city" VARCHAR(255) DEFAULT '', "state" VARCHAR(255) DEFAULT '', "country" VARCHAR(255));
CREATE TABLE IF NOT EXISTS "seriespost" ("yearID" INTEGER, "round" VARCHAR(255) DEFAULT '', "teamIDwinner" VARCHAR(255) DEFAULT '', "lgIDwinner" VARCHAR(255) DEFAULT '', "teamIDloser" VARCHAR(255) DEFAULT '', "lgIDloser" VARCHAR(255) DEFAULT '', "wins" INTEGER, "losses" INTEGER, "ties" INTEGER, PRIMARY KEY ("yearID", "round"));
CREATE TABLE IF NOT EXISTS "teams" ("yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "teamID" VARCHAR(255) DEFAULT '', "franchID" VARCHAR(255) DEFAULT '', "divID" VARCHAR(255) DEFAULT '', "Rank" INTEGER, "G" INTEGER, "Ghome" INTEGER, "W" INTEGER, "L" INTEGER, "DivWin" VARCHAR(255) DEFAULT '', "WCWin" VARCHAR(255) DEFAULT '', "LgWin" VARCHAR(255) DEFAULT '', "WSWin" VARCHAR(255) DEFAULT '', "R" INTEGER, "AB" INTEGER, "H" INTEGER, "doubles" INTEGER, "triples" INTEGER, "HR" INTEGER, "BB" INTEGER, "SO" INTEGER, "SB" INTEGER, "CS" INTEGER, "HBP" INTEGER, "SF" INTEGER, "RA" INTEGER, "ER" INTEGER, "ERA" REAL, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "HA" INTEGER, "HRA" INTEGER, "BBA" INTEGER, "SOA" INTEGER, "E" INTEGER, "DP" INTEGER, "FP" REAL, "name" VARCHAR(255) DEFAULT '', "park" VARCHAR(255) DEFAULT '', "attendance" INTEGER, "BPF" INTEGER, "PPF" INTEGER, "teamIDBR" VARCHAR(255) DEFAULT '', "teamIDlahman45" VARCHAR(255) DEFAULT '', "teamIDretro" VARCHAR(255) DEFAULT '', PRIMARY KEY ("yearID", "lgID", "teamID"));
CREATE TABLE IF NOT EXISTS "teamshalf" ("yearID" INTEGER, "lgID" VARCHAR(255) DEFAULT '', "teamID" VARCHAR(255) DEFAULT '', "Half" INTEGER, "divID" VARCHAR(255) DEFAULT '', "DivWin" VARCHAR(255) DEFAULT '', "Rank" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER, PRIMARY KEY ("yearID", "teamID", "Half"));
CREATE TABLE IF NOT EXISTS "teamsfranchises" ("franchID" VARCHAR(255) PRIMARY KEY, "franchName" VARCHAR(255) DEFAULT '', "active" VARCHAR(255) DEFAULT '', "NAassoc" VARCHAR(255));
